name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:12.3
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password1234
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Build and run tests
        env:
          DATABASE_URL: postgres://postgres@localhost:5432/ignob-backend-api_test
          RAILS_ENV: test
          APP_NAME: Ignob
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          CLIENT_URL: https://ignob.com
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_ACCOUNT_ACTIVATION: ${{ secrets.JWT_ACCOUNT_ACTIVATION }}
          JWT_RESET_PASSWORD: ${{ secrets.JWT_RESET_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_USERNAME: ${{ secrets.SENDGRID_USERNAME }}
          SENDGRID_PASSWORD: ${{ secrets.SENDGRID_PASSWORD }}
          FB_APP_ID: ${{ secrets.FB_APP_ID }}
          FB_APP_SECRET: ${{ secrets.FB_APP_SECRET }}
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install
          bundle exec rails db:setup
          bundle exec rails test
